### ISSUE TITLE
Text Box Does Not Appear In Plugin Menu

### ISSUE THREAD

**Issue by Gtt1229** [CinderBlocc/OnlineStatusChanger#2]
Text box to change status does not appear in menu.

Bakkes ver: 164

![bakkesmod](https://user-images.githubusercontent.com/23534272/172068528-a321a617-3681-4e15-982c-2c749773c552.png)

I edited my status via the settings file, but prior, no text box was displayed.

**Comment by CinderBlocc** [comment]
Do you have the plugin loaded? You might need to add it to your auto-load list if it isn't. IIRC textboxes dont show up when their cvars don't exist.
