### ISSUE TITLE
Discord RPC still affected by plugin after disabling online status and even uninstalling the plugin

### ISSUE THREAD

**Issue by horizon1g** [CinderBlocc/OnlineStatusChanger#4]
tried disabling it in the plugins ui, plugin manager and even uninstalling all configs and the plugin dll, didnt fix it
![image](https://github.com/CinderBlocc/OnlineStatusChanger/assets/116465892/c74308e8-2d55-4008-b7e4-82cab45ff4f6)
![image](https://github.com/CinderBlocc/OnlineStatusChanger/assets/116465892/af857fba-774e-4c23-9dea-8e7f3eae52cb)

i reinstalled it and tried uninstalling again but it still doesnt remove the RPC status on discord

**Comment by CinderBlocc** [comment]
This plugin is just a GUI wrapper for the `cl_online_status_override` cvar in the core of BakkesMod. Setting that cvar directly should fix your issue. If that doesn't work, then I'm not sure. However, it wouldn't be an issue with this plugin itself, so I'll close out the ticket

**Comment by horizon1g** [comment]
yea my bad, i just saw the closed issues tab a few seconds ago and realized i made this issue for no reason, thanks for the response though, the issue is solved
